name = "qingstor"

[namespace.service.new]
required = ["credential"]
optional = ["default_service_pairs", "endpoint", "http_client_options"]

[namespace.service.op.create]
required = ["location"]

[namespace.service.op.delete]
optional = ["location"]

[namespace.service.op.get]
optional = ["location"]

[namespace.service.op.list]
optional = ["location"]

[namespace.storage]
implement = ["copier", "fetcher", "mover", "multiparter", "reacher"]

[namespace.storage.new]
required = ["name"]
optional = ["default_storage_pairs", "disable_uri_cleaning", "http_client_options", "location", "pair_policy", "work_dir"]

[namespace.storage.op.create]
optional = ["multipart_id"]

[namespace.storage.op.delete]
optional = ["multipart_id"]

[namespace.storage.op.list]
optional = ["list_mode"]

[namespace.storage.op.reach]
required = ["expire"]

[namespace.storage.op.read]
optional = ["offset", "io_callback", "size", "sse_customer_algorithm", "sse_customer_key", "sse_customer_key_md5"]

[namespace.storage.op.write]
optional = ["content_md5", "content_type", "io_callback", "storage_class", "sse_customer_algorithm", "sse_customer_key", "sse_customer_key_md5"]

[namespace.storage.op.copy]
optional = ["sse_customer_algorithm", "sse_customer_key", "sse_customer_key_md5", "sse_copy_source_customer_algorithm", "sse_copy_source_customer_key", "sse_copy_source_customer_key_md5"]

[namespace.storage.op.create_multipart]
optional = ["sse_customer_algorithm", "sse_customer_key", "sse_customer_key_md5"]

[namespace.storage.op.write_multipart]
optional = ["sse_customer_algorithm", "sse_customer_key", "sse_customer_key_md5"]

[pairs.sse_customer_algorithm]
type = "string"
description = "specifies the encryption algorithm. Only AES256 is supported now."

[pairs.sse_customer_key]
type = "string"
description = "is the customer-provided encryption key. For AES256 keys, the plaintext must be 32 bytes long. The key must be Base64 encoded."

[pairs.sse_customer_key_md5]
type = "string"
description = "is the MD5 of the customer-provided key. The key MD5 must be Base64 encoded."

[pairs.sse_copy_source_customer_algorithm]
type = "string"
description = "is the encryption algorithm for the source object. Only AES256 is supported now."

[pairs.sse_copy_source_customer_key]
type = "string"
description = "is the customer-provided encryption key for the source object. For AES256 keys, the plaintext must be 32 bytes long. The key must be Base64 encoded."

[pairs.sse_copy_source_customer_key_md5]
type = "string"
description = "is the MD5 of the customer-provided key for the source object. The key MD5 must be Base64 encoded."

[pairs.disable_uri_cleaning]
type = "bool"

[pairs.storage_class]
type = "string"

[pairs.default_service_pairs]
type = "DefaultServicePairs"
description = "set default pairs for service actions"

[pairs.default_storage_pairs]
type = "DefaultStoragePairs"
description = "set default pairs for storager actions"

[infos.object.meta.storage-class]
type = "string"

[infos.object.meta.sse_customer_algorithm]
type = "string"